# FROM pytorch:transformers

# RUN mamba install -y -n transformers 

# Image Name: pytorch:crowd_sourcing
# ビルドの例
# docker compose -f ~/university/LLM/crowd_sourcing/.devcontainer/docker-compose.yml build
